[package]
name = "codespan_preprocessed"
version = "0.2.0"
authors = ["Xophe <christophe.dousson@orange.com>"]
edition = "2018"
license = "MIT"
description = "Beautiful diagnostic reporting for preprocessed text files"
repository = "https://github.com/XopheD/codespan_preprocessed"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codespan-reporting = "0.11"

[dev-dependencies]
unindent = "0.1"
